const values = {
    
    'Aerobics': 6,
    'Backpacking': 7,
    'Badminton (singles)': 4.5,
    'Baseball': 5,
    'Basketball (half-court)': 6,
    'Bicycling indoors (stationary bike) ': 5,
    'Bicycling stationary 100 w light effort ': 5.5,
    'Bicycling stationary 150 w moderate effort ': 7,
    'Bicycling outdoors < 10 mph leisure': 4,
    'Bicycling outdoors 10 - 11.9 mph leisure light effort': 6,
    'Bicycling outdoors 12 - 13.9 mph leisure moderate effort': 8,
    'Bicycling outdoors 14 - 15.9 mph fast or visorous effort': 1,
    'Calisthenics pushups pullups situps vigorous effort': 8,
    'Calisthenics home exercise light or moderate effort': 4.5,
    'Conditioning exercise circuit training general': 8,
    'Canoeing 2.0 - 3.9 mph light effort': 3,
    'Kayaking': 5,
    'Dancing ballet': 6,
    'Dancing ballroom slow': 3,
    'Dancing disco': 5.5,
    'Dancing line': 4.5,
    'Dancing swing': 5.5,
    'Dancing (really kicking up your heels)': 5.5,
    'Dusting': 2.5,
    'Elliptical machine': 5.5,
    'Football': 8,
    'Frisbee': 3,
    'Gardening': 5,
    'Golfing (no carts please) carrying clubs': 5.5,
    'Grocery shopping': 3.5,
    'Handball': 1,
    'Hiking': 6,
    'Home repair (building hammering)': 4.5,
    'Horseback riding': 2.5,
    'Housecleaning': 3.5,
    'Ice hockey': 8,
    'Ice skating': 7,
    'Ironing': 2.3,
    'Jogging': 7,
    'Running 5 mph ( 12 min mile)': 8,
    'Running 6 mph 10 min mile': 1,
    'Running 8 mph 7.5 min mile': 1.5,
    'Karate': 1,
    'Kickboxing': 1,
    'Lacrosse': 8,
    'Laundry/folding clothes': 2,
    'Making the bed ': 2,
    'Mopping/scrubbing floors': 4.5,
    'Mowing the lawn (no riding mowers please)': 4.5,
    'Painting the house': 5,
    'Pilates': 6,
    'Ping pong': 4,
    'Playing with kids at the playground': 4,
    'Playing musical instrument - drums': 4,
    'Playing musical instrument - guitar': 2,
    'Playing musical instrument - piano': 2.5,
    'Cooking': 2.5,
    'Racquetball': 7,
    'Raking': 4,
    'Rearranging furniture': 6,
    'Rock climbing (ascending)': 1,
    'Rock climbing (repelling)': 8,
    'Roller blading/skating': 7,
    'Rope jumping': 8,
    'Rowing': 7,
    'Rugby': 1,
    'Shoveling snow': 6,
    'Sledding': 7,
    'Snow skiing (cross-country)': 8,
    'Snow skiing (downhill)': 6,
    'Indoor skiing (on a machine)': 9.5,
    'Soccer': 7,
    'Softball': 5,
    'Stacking firewood for winter': 5,
    'Stair climbing': 6,
    'Surfing': 3,
    'Sweeping (inside)': 2.5,
    'Swimming': 6,
    'Taekwondo': 1,
    'Tai chi': 4,
    'Tennis (doubles)': 6,
    'Tennis (singles)': 8,
    'Vacuuming': 2.5,
    'Volleyball (beach)': 8,
    'Volleyball (casual game)': 3,
    'Walking (briskly)': 4,
    'Walking to work or class leisure': 4,
    'Walking pushing a stroller': 2.5,
    'Walking with the dog': 3.5,
    'Washing the car ': 4.5,
    'Washing the dishes': 2.3,
    'Washing windows': 4.5,
    'Water aerobics ': 4,
    'Water polo': 1,
    'Water skiing': 6,
    'Weight lifting': 3,
    'Whitewater rafting ': 5,
    'Yoga hatha': 4

  };


const exercises = Object.keys(values);

  
export {values, exercises};